#!/usr/bin/env python3
import argparse, subprocess, os
from src.vertical_reduction import trace_context, delta_debug
from src.config import INFO_OUTPUT, TEMP_OUTPUT
from src.helper import get_queries, read_info, write_queries

def run_test(test: str, query_path: str, oracle: str, queries: list[str] = []):
    if queries:
        os.makedirs(os.path.dirname(query_path), exist_ok=True)
        with open(query_path, "w") as f:
            for query in queries:
                f.write(query + "\n")
    try:
        result = subprocess.run(
            [test, query_path, oracle],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True
        )
        return result.returncode == 0
    except subprocess.TimeoutExpired:
        print("Test script timed out.")
        return False

def main():
    parser = argparse.ArgumentParser(description="SQL Query Reducer")
    parser.add_argument("--query", required=True, help="Path to SQL query file")
    parser.add_argument("--test", required=True, help="Shell script to test for the bug")
    args = parser.parse_args()

    # path setup
    original_path = os.path.join(args.query, "original_test.sql")
    reduced_path = os.path.join(args.query, "reduced_test.sql")
    info_path = os.path.join(INFO_OUTPUT, "info.txt")
    os.makedirs(os.path.dirname(info_path), exist_ok=True)
    with open(info_path, "w") as f:
        f.write("") 
    with open(os.path.join(args.query, "oracle.txt"), "r") as f:
        oracle = str(f.read().strip())

    # reduction
    run_test(args.test, original_path, oracle)
    queries = get_queries(original_path)
    print(len(queries))

    # trace context reduction
    index, errlist, msg = read_info(info_path)
    setup_queries, context_queries, bug_query = trace_context(queries, index, errlist, msg) # type: ignore
    write_queries(reduced_path, setup_queries + context_queries + bug_query)
    if run_test(args.test, reduced_path, oracle):
        print(len(setup_queries + context_queries + bug_query))

    # first delta debug reduction
    temp_path = os.path.join(TEMP_OUTPUT, "delta.sql")
    if len(queries) > 50:
        delta_queries = setup_queries + delta_debug(setup_queries, context_queries, bug_query, lambda q: run_test(args.test, temp_path, oracle, q), n=2) + bug_query
    else:
        delta_queries = delta_debug([], setup_queries + context_queries + bug_query, [], lambda q: run_test(args.test, temp_path, oracle, q), n=2)
    write_queries(reduced_path, delta_queries)
    if run_test(args.test, reduced_path, oracle):
        print(len(delta_queries))

    # second delta debug reduction
    if len(queries) > 50:
        delta_queries = delta_debug([], delta_queries, [], lambda q: run_test(args.test, temp_path, oracle, q), n=2)
        write_queries(reduced_path, delta_queries)
        if run_test(args.test, reduced_path, oracle):
            print(len(delta_queries))

if __name__ == "__main__":
    main()
