CREATE TABLE T1 ( c1 JSON , c2 INT , c3 ) ;
CREATE TABLE T2 ( c1 NOT NULL DEFAULT NULL , c2 ) ;
CREATE TABLE T3 ( c1 , c2 , c3 ) ;
SELECT ( SELECT ROW_NUMBER ( ) OVER ( ORDER BY c.c2 ) FROM T3 ) , DENSE_RANK ( ) OVER ( ORDER BY a.c2 ) FROM T1 AS a INNER JOIN T2 AS b ON a.c1 = b.c2 INNER JOIN T3 AS c ON b.c1 = c.c2 WHERE a.c2 > c.c2 AND b.c1 > a.c1 GROUP BY a.c2 ;
