CREATE TABLE t1 ( col2 , col3 , col4 ) ;
INSERT INTO t1 ( col4 ) VALUES ( 'TOODVU' ) ;
INSERT INTO t1 ( col4 ) VALUES ( 'RxYwTBHZ3' ) ;
SELECT LAG ( -403961669 ) OVER ( ) , AVG ( 'HAFG' ) OVER ( PARTITION BY col4 ) , ROW_NUMBER ( ) OVER ( RANGE BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING ) FROM t1 ;
